/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgActivitiesHackathonRouteImport } from './routes/org/activities/hackathon'

const OrgActivitiesPostsLazyRouteImport = createFileRoute(
  '/org/activities/posts',
)()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgActivitiesPostsLazyRoute = OrgActivitiesPostsLazyRouteImport.update({
  id: '/org/activities/posts',
  path: '/org/activities/posts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/org/activities/posts.lazy').then((d) => d.Route),
)
const OrgActivitiesHackathonRoute = OrgActivitiesHackathonRouteImport.update({
  id: '/org/activities/hackathon',
  path: '/org/activities/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/org/activities/hackathon': typeof OrgActivitiesHackathonRoute
  '/org/activities/posts': typeof OrgActivitiesPostsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/org/activities/hackathon': typeof OrgActivitiesHackathonRoute
  '/org/activities/posts': typeof OrgActivitiesPostsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/org/activities/hackathon': typeof OrgActivitiesHackathonRoute
  '/org/activities/posts': typeof OrgActivitiesPostsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/org/activities/hackathon' | '/org/activities/posts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/org/activities/hackathon' | '/org/activities/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/org/activities/hackathon'
    | '/org/activities/posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrgActivitiesHackathonRoute: typeof OrgActivitiesHackathonRoute
  OrgActivitiesPostsLazyRoute: typeof OrgActivitiesPostsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/activities/posts': {
      id: '/org/activities/posts'
      path: '/org/activities/posts'
      fullPath: '/org/activities/posts'
      preLoaderRoute: typeof OrgActivitiesPostsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/activities/hackathon': {
      id: '/org/activities/hackathon'
      path: '/org/activities/hackathon'
      fullPath: '/org/activities/hackathon'
      preLoaderRoute: typeof OrgActivitiesHackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrgActivitiesHackathonRoute: OrgActivitiesHackathonRoute,
  OrgActivitiesPostsLazyRoute: OrgActivitiesPostsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
